In [6]:
class vechile():
    def __init__(self, P, R):
        self.P= P
        self.R= R
class Car(vechile):
    def __init__(self, P, R, S):
        super(). __init__ (P, R)
        self.S=S
    def getSeats(self):
        txt= self.P + 'turi' + str(self.S) + 'sed vietu'
        return txt
    
test = Car( P='pavadinimas', R=5000, S= 200)

print(test.getSeats())

class Train(vechile):
    def __init__(self, P, R, S):
        super(). __init__ (P, R)
        self.S=S
    def getSeats(self):
        txt= self.P + 'turi' + str(self.S) + 'sed vietu'
        return txt
    
test = Train( P='pavadinimas', R=5000, S= 200)

print(test.getSeats())

class Bus(vechile):
    def __init__(self, P, R, S):
        super(). __init__ (P, R)
        self.S=S
    def getSeats(self):
        txt= self.P + 'turi' + str(self.S) + 'sed vietu'
        return txt
    
test = Train( P='pavadinimas', R=5000, S= 200)

print(test.getSeats())


pavadinimasturi200sed vietu
pavadinimasturi200sed vietu
pavadinimasturi200sed vietu


In [38]:
#parašykite klasę TxtAnalyzer, kuriai kreipimosi metu galima būtų nurodyti failo pavadinimą ir stulpelių skirtuką.
#klasė sukūrimo metu turi nuskaityti failą, stulpelius skaičių suskirstyti
# į sąrašus ir juos priskirti atributams X, Y ir Z.
#Realizuokite metodus, kurie grąžintų X, Y, Z sąrašų vidurkius, minimalias ir maksimalias vertes.
# Pythone yra min, max, sum funkcijos

import os
os.getcwd()

class TxtAnalyzer():

    def __init__(self, pavadinimas, skirtukas):
        self.pavadinimas= pavadinimas
        self.skirtukas = skirtukas
        self.x = []
        self.y = []
        self.z = []
        pass
    def TxtReader(self):
        fname = self.pavadinimas
        f= open(fname, mode = 'r', encoding= 'utf-8')

        turinys = f.readlines()

        f.close()
        for i in turinys:
            self.x.append(float(i.split(self.skirtukas)[0]))
            self.y.append(float(i.split(self.skirtukas)[1]))
            self.z.append(float(i.split(self.skirtukas)[2]))
        print(self.x)
        print(self.y)
        print(self.z)
    def getVidurkis(self):
        vidurkisx= sum(self.x)/len(self.x)
        vidurkisy= sum(self.y)/len(self.y)
        vidurkisz= sum(self.z)/len(self.z)
        print(vidurkisx)
        print(vidurkisy)
        print(vidurkisz)
    def getmin(self):
        minx= min(self.x)
        miny= min(self.y)
        minz= min(self.z)
        return minx, miny, minz
    def getmax(self):
        maxx= max(self.x)
        maxy= max(self.y)
        maxz= max(self.z)
        return maxx, maxy, maxz
            
test= TxtAnalyzer(pavadinimas = 'data0.txt',skirtukas= ';')
test.TxtReader()
print(test.getVidurkis())
print(test.getmin())
print(test.getmax())

[52.0, 11.0, 55.0, 55.0, 47.0, 71.0, 49.0, 48.0, 82.0, 24.0, 13.0, 95.0, 22.0, 95.0, 32.0, 35.0, 86.0, 90.0, 8.0, 21.0, 23.0, 92.0, 38.0, 99.0, 29.0, 93.0, 53.0, 87.0, 47.0, 38.0, 38.0, 36.0, 83.0, 79.0, 2.0, 18.0, 86.0, 78.0, 51.0, 7.0, 65.0, 9.0, 50.0, 59.0, 91.0, 39.0, 36.0, 16.0, 73.0, 54.0, 79.0, 47.0, 97.0, 0.0, 18.0, 54.0, 93.0, 79.0, 62.0, 63.0, 22.0, 49.0, 19.0, 43.0, 65.0, 0.0, 80.0, 70.0, 95.0, 58.0, 47.0, 89.0, 99.0, 94.0, 70.0, 41.0, 60.0, 18.0, 12.0, 3.0, 28.0, 50.0, 33.0, 52.0, 99.0, 41.0, 1.0, 58.0, 60.0, 5.0, 3.0, 44.0, 83.0, 51.0, 58.0, 27.0, 71.0, 96.0, 18.0, 83.0]
[0.3666, 0.8672, 0.9966, 0.7318, 0.6703, 0.2205, 0.4725, 0.5563, 0.5348, 0.3462, 0.784, 0.348, 0.8328, 0.5423, 0.3351, 0.1916, 0.1262, 0.5941, 0.914, 0.7839, 0.7763, 0.8757, 0.4502, 0.6906, 0.8418, 0.1275, 0.1101, 0.3211, 0.5525, 0.5458, 0.8458, 0.6115, 0.5083, 0.7373, 0.9759, 0.7192, 0.0424, 0.4218, 0.8271, 0.796, 0.2074, 0.0712, 0.0602, 0.1218, 0.5095, 0.4785, 0.9309, 0.9365, 0.918, 0.8063, 0.6445, 0.245

In [41]:
class TxtAnalyzer():
    def __init__(self, pav, skirtukas):
        self.pavadinimas = pav
        self.skirt = skirtukas
        self.x = []
        self.y = []
        self.z = []
        pass
    def TxtReader(self):
        fname = self.pavadinimas
        f = open(fname, mode='r', encoding='utf-8')
        tekstas = f.readlines()
        print(tekstas)
        f.close()
        for x in tekstas:
            self.x.append(float(x.split(self.skirt)[0]))
            self.y.append(float(x.split(self.skirt)[1]))
            self.z.append(float(x.split(self.skirt)[2]))
        print(self.x)
        print(self.y)
        print(self.z)
    def getVidurkis(self):
        vidurkisX = sum(self.x)/len(self.x)
        vidurkisY = sum(self.y)/len(self.y)
        vidurkisZ = sum(self.z)/len(self.z)
        
        return vidurkisX, vidurkisY, vidurkisZ
    
    def getMinimali(self):
        minimaliX = min(self.x)
        minimaliY = min(self.y)
        minimaliZ = min(self.z)
        return minimaliX, minimaliY, minimaliZ
    
    def getMax(self):
        minimaliX = max(self.x)
        minimaliY = max(self.y)
        minimaliZ = max(self.z)
        return minimaliX, minimaliY, minimaliZ


z = TxtAnalyzer('data0.txt',';')
z.TxtReader()
print(z.getVidurkis())
print(z.getMinimali())
print(z.getMax())

['52;0.3666;19.0616\n', '11;0.8672;9.5391\n', '55;0.9966;54.8137\n', '55;0.7318;40.2481\n', '47;0.6703;31.5026\n', '71;0.2205;15.6522\n', '49;0.4725;23.1545\n', '48;0.5563;26.7004\n', '82;0.5348;43.8516\n', '24;0.3462;8.3078\n', '13;0.784;10.1921\n', '95;0.348;33.0584\n', '22;0.8328;18.3206\n', '95;0.5423;51.5156\n', '32;0.3351;10.722\n', '35;0.1916;6.7055\n', '86;0.1262;10.8526\n', '90;0.5941;53.47\n', '8;0.914;7.3119\n', '21;0.7839;16.4628\n', '23;0.7763;17.8547\n', '92;0.8757;80.5658\n', '38;0.4502;17.1066\n', '99;0.6906;68.37\n', '29;0.8418;24.4108\n', '93;0.1275;11.8609\n', '53;0.1101;5.8339\n', '87;0.3211;27.9361\n', '47;0.5525;25.9672\n', '38;0.5458;20.7417\n', '38;0.8458;32.1402\n', '36;0.6115;22.0154\n', '83;0.5083;42.1888\n', '79;0.7373;58.2501\n', '2;0.9759;1.9518\n', '18;0.7192;12.9463\n', '86;0.0424;3.6446\n', '78;0.4218;32.9034\n', '51;0.8271;42.1807\n', '7;0.796;5.5719\n', '65;0.2074;13.4795\n', '9;0.0712;0.6406\n', '50;0.0602;3.0117\n', '59;0.1218;7.1866\n', '91;0.5095;

In [42]:
class TxtAnalyzer:
    def __init__(self, fileName, dell=';'):
        self.fileName = fileName
        self.dell = dell
        self.X, self.Y, self.Z = self.readFile()
    def readFile(self):
        X, Y, Z = [], [], []
        try:
             with open(self.fileName, 'r') as file:
                for line in file:
                    values = line.strip().split(self.dell)
                    if len(values) == 3:
                        X.append(float(values[0]))
                        Y.append(float(values[1]))
                        Z.append(float(values[2]))
        except FileNotFoundError:
            print("File not found!")
        return X, Y, Z
    def Ave(self, data):
        if data:
            return sum(data)/len(data)
        else:
            return None
    def Min(self, data):
        if data:
            return min(data)
        else:
            return None
    def Max(self, data):
        if data:
            return max(data)
        else:
            return None
fileName = "data0.txt"  
analyzer = TxtAnalyzer(fileName)
print("X: ")
print("Ave:", analyzer.Ave(analyzer.X))
print("Min:", analyzer.Min(analyzer.X))
print("Max:", analyzer.Max(analyzer.X))
print("\nY: ")
print("Ave:", analyzer.Ave(analyzer.Y))
print("Min:", analyzer.Min(analyzer.Y))
print("Max:", analyzer.Max(analyzer.Y))
print("\nZ: ")
print("Ave:", analyzer.Ave(analyzer.Z))
print("Min:", analyzer.Min(analyzer.Z))
print("Max:", analyzer.Max(analyzer.Z))

X: 
Ave: 51.47
Min: 0.0
Max: 99.0

Y: 
Ave: 0.546122
Min: 0.0196
Max: 0.9966

Z: 
Ave: 27.091621
Min: 0.0
Max: 86.4277


In [43]:
x= [1,2,3,4,5]
x1=[]
for i in x:
    x1.append(i-0.75)
print(x1)

[0.25, 1.25, 2.25, 3.25, 4.25]


In [8]:
import numpy as np

[autoreload of modulis failed: Traceback (most recent call last):
  File "C:\Users\37060\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\IPython\extensions\autoreload.py", line 276, in check
    superreload(m, reload, self.old_objects)
  File "C:\Users\37060\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\IPython\extensions\autoreload.py", line 475, in superreload
    module = reload(module)
             ^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.752.0_x64__qbz5n2kfra8p0\Lib\importlib\__init__.py", line 131, in reload
    _bootstrap._exec(spec, module)
  File "<frozen importlib._bootstrap>", line 866, in _exec
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootst

In [45]:
# array
x = np.arange(0,10)
print(x)
print(type(x))

[0 1 2 3 4 5 6 7 8 9]
<class 'numpy.ndarray'>


In [46]:
y= x- 0.75
print(y)

[-0.75  0.25  1.25  2.25  3.25  4.25  5.25  6.25  7.25  8.25]


In [ ]:
np.average()
np.min()
np.mean()
np.median()

In [47]:
a_list=[i for i in range(1,11)]
print(a_list)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [48]:
a_array=np.asarray(a_list)
print(a_array+0.75)

[ 1.75  2.75  3.75  4.75  5.75  6.75  7.75  8.75  9.75 10.75]


In [51]:
x=[1,2,3]
y=[4,5,6]
x_np=np.asarray(x)
y_np=np.asarray(y)
print(x_np+y_np)
c=x_np*y_np
print(c)

[5 7 9]
[ 4 10 18]


In [52]:
np.min(x)
np.max(y_np)

6

In [55]:
atsitiktinis=np.random.randint(0,10,100) #3 sk- kiek element7 bus
print(atsitiktinis)

[3 0 1 2 0 5 3 5 6 1 6 0 1 0 7 4 5 1 6 4 7 2 8 1 1 4 1 9 5 4 3 6 5 6 5 1 4
 5 4 5 9 3 2 1 7 2 6 1 3 8 1 3 5 7 7 5 7 8 2 7 3 6 7 7 0 1 4 4 0 0 6 0 1 5
 2 5 0 2 9 4 3 5 8 6 8 4 2 8 9 9 1 7 1 6 3 3 3 4 4 1]


In [58]:
atsitiktinis_float=np.random.rand(100) #griežtai ribos nuuo 0 iki 1
print(atsitiktinis_float)

[0.30456685 0.94904635 0.42272687 0.63618332 0.08864201 0.9397973
 0.36769308 0.63537257 0.95359881 0.54944597 0.33035747 0.23130317
 0.45745138 0.99929705 0.0812918  0.8678333  0.34999191 0.2710028
 0.04679577 0.34437717 0.25837885 0.21045063 0.39433842 0.05945312
 0.37984525 0.87534435 0.38135282 0.72580144 0.80276445 0.88189344
 0.16693941 0.27829293 0.46061294 0.20290642 0.95533251 0.81253919
 0.44917089 0.97865832 0.88695908 0.25608531 0.97627784 0.51604349
 0.54963543 0.94597339 0.63337211 0.09085295 0.08155328 0.32472673
 0.93766714 0.00462202 0.703303   0.7191885  0.16768424 0.27049747
 0.22850349 0.41028674 0.32175908 0.88164538 0.65148905 0.02816449
 0.714129   0.57473234 0.78302162 0.23117429 0.15244538 0.91403389
 0.95862612 0.03625108 0.82061806 0.07789065 0.99685831 0.18035029
 0.66268641 0.01378893 0.89545572 0.73279577 0.48959414 0.32530833
 0.9842269  0.82692444 0.06733167 0.79015408 0.97535988 0.63409283
 0.61356797 0.74464928 0.24822104 0.34624878 0.88942967 0.014163

In [81]:
xas= np.random.randint(1,10,100) #visada generuojami skiringi sk ,tod4l ir ats skiraisi
svoriai = np.random.rand(100)
#mean ir average
vidurkis= np.mean(xas)
print(vidurkis)
sv_vid=np.average(xas,weights=svoriai)# weight= svertinis koeficientas
print(sv_vid)
#median()
medx= np.median(xas)
print(medx, np.min(xas), np.max(xas))


5.42
5.453933659529201
6.0 1 9


In [84]:
l= np.linspace(1,10,10)
print(l)

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]


In [88]:
#asaray, arange, min, max, mean, average, median
n_np=np.arange(0,10)
#kaip metodai
minn=n_np.min()
print(minn)
print(n_np.mean()) #Mean - aritmetinis vidurkis
print(n_np.max())

0
4.5
9


In [2]:
%load_ext autoreload

In [3]:
%autoreload 2

In [4]:
import modulis


pavadinimasturi 200 sed vietu
pavadinimasturi 200 sed vietu
pavadinimasturi 200 sed vietu


In [5]:
print(modulis.A)

7


In [6]:
modulis.printA()

as esu funkcija


In [7]:
# iškelkite savo anksčiau rašytas Vehicle, Car, etc klases
# į modulį
# ir patikrinkite klasių veikimą
# sukurdami kintamuosius ir patikrindami jų veikimą
test = modulis.Train( P='Trainkinys ', R=5000, S= 200)
print(test.getSeats())

test1 = modulis.Car( P='Masina ', R=5000, S= 120)
print(test1.getSeats())

test2 = modulis.Bus( P='Autobusas ', R=5000, S= 2)

print(test2.getSeats())

Trainkinys turi 200 sed vietu
Masina turi 120 sed vietu
Autobusas turi 2 sed vietu


In [9]:
#sukurkite failus nuskaitančią klasę, ji turi būti aprašyta jūsų kuriamame modulyje;
#ta klasė turi nuskaityti pateiktą failą, ir suskaidyti stulpelius į sąrašus:
#sąrašai I, U, j, P, duomenys iš juos iš atitinkamų taip pat pavadintų stulpelių
#realizuokite tai, jog klasė rastų tokį dydį - maksimalų P, suskaičiuotų tokį dydį pce = Pmax / 1000 * 100%;
#šie dydžiai turi būti pasiekiamį arba kaip atributas, arba galite įdėti metodą jam gauti
import numpy as np


In [22]:
testasas= modulis.failai('V1145_A_3k_FW_2.03',';')
print(testasas.maxp())

ValueError: max() iterable argument is empty

In [51]:
import modulis2
tst=modulis2.failai('123.dat',';')
tst.read()
print(tst.maxp())
print(tst.getpce())
#Bonus, kas atliko - pabandykite realizuoti radimą tokių verčių: j kai U = 0 (arba close to zero), 
#U, kai j =0 (arba close to zero), jie turi specialius žymėjimus jsc ir Uoc.

['U[V] ; I[A] ; j[mA/cm^2] ; P[mW/cm^2]\n', '1.2 ; 0.0005167 ; 6.4587625 ; 7.750515\n', '1.1766667 ; 0.0005105 ; 6.3817112 ; 7.5091469\n', '1.1533333 ; 0.0004552 ; 5.6900225 ; 6.5624926\n', '1.13 ; 0.0003836 ; 4.7946613 ; 5.4179672\n', '1.1066667 ; 0.0003048 ; 3.8098413 ; 4.2162243\n', '1.0833333 ; 0.0002241 ; 2.80134 ; 3.034785\n', '1.06 ; 0.0001429 ; 1.7864875 ; 1.8936767\n', '1.0366667 ; 6.38e-05 ; 0.7976935 ; 0.8269423\n', '1.0133333 ; -1.43e-05 ; -0.1792418 ; -0.1816316\n', '0.99 ; -9.23e-05 ; -1.1542955 ; -1.1427525\n', '0.9666667 ; -0.0001648 ; -2.0604813 ; -1.9917985\n', '0.9433333 ; -0.0002385 ; -2.9815475 ; -2.8125931\n', '0.92 ; -0.0003079 ; -3.8486588 ; -3.540766\n', '0.8966667 ; -0.0003758 ; -4.69809 ; -4.2126207\n', '0.8733333 ; -0.0004409 ; -5.5114387 ; -4.8133232\n', '0.85 ; -0.0005058 ; -6.3226512 ; -5.3742536\n', '0.8266667 ; -0.0005672 ; -7.0894987 ; -5.8606523\n', '0.8033333 ; -0.0006257 ; -7.8210212 ; -6.2828871\n', '0.78 ; -0.0006826 ; -8.533085 ; -6.6558063\n', '